#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Autoformat
Version  : 1.74
Release  : 11
URL      : http://search.cpan.org/CPAN/authors/id/N/NE/NEILB/Text-Autoformat-1.74.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/N/NE/NEILB/Text-Autoformat-1.74.tar.gz
Summary  : 'Automatic text wrapping and reformatting'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-Text-Autoformat-doc
BuildRequires : perl(Text::Reform)

%description
This archive contains the distribution Text-Autoformat,
version 1.74:
Automatic text wrapping and reformatting

%package doc
Summary: doc components for the perl-Text-Autoformat package.
Group: Documentation

%description doc
doc components for the perl-Text-Autoformat package.


%prep
%setup -q -n Text-Autoformat-1.74

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/Autoformat.pm
/usr/lib/perl5/site_perl/5.26.1/Text/Autoformat/Hang.pm
/usr/lib/perl5/site_perl/5.26.1/Text/Autoformat/NullHang.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
